# Generated by Django 5.2.4 on 2025-07-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='produt',
            new_name='product',
        ),
    ]
