# Generated by Django 5.2.4 on 2025-07-31 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
